In [89]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [90]:
# Read in the data
df = pd.read_csv('./src/car_dataset_origin.csv')

In [91]:
df.head()

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [92]:

df = df.rename(columns={'symboling': 'etat_de_route', 'CarName': 'marque_voiture', 'fueltype': 'carburant', 'aspiration': 'turbo', 'doornumber': 'nombre_portes', 'carbody': 'type_vehicule', 'drivewheel': 'transmission', 'enginelocation': 'emplacement_moteur', 'wheelbase': 'empattement', 'carlength': 'longueur_voiture', 'carwidth': 'largeur_voiture', 'carheight': 'hauteur_voiture', 'curbweight': 'poids_vehicule', 'enginetype': 'type_moteur', 'cylindernumber': 'nombre_cylindres', 'enginesize': 'taille_moteur', 'fuelsystem': 'systeme_carburant', 'boreratio': 'taux_alésage', 'stroke': 'course', 'compressionratio': 'taux_compression', 'horsepower': 'chevaux', 'peakrpm': 'tour_moteur', 'citympg': 'consommation_ville', 'highwaympg': 'consommation_autoroute', 'price': 'prix'})

df.columns

Index(['car_ID', 'etat_de_route', 'marque_voiture', 'carburant', 'turbo',
       'nombre_portes', 'type_vehicule', 'transmission', 'emplacement_moteur',
       'empattement', 'longueur_voiture', 'largeur_voiture', 'hauteur_voiture',
       'poids_vehicule', 'type_moteur', 'nombre_cylindres', 'taille_moteur',
       'systeme_carburant', 'taux_alésage', 'course', 'taux_compression',
       'chevaux', 'tour_moteur', 'consommation_ville',
       'consommation_autoroute', 'prix'],
      dtype='object')

In [93]:
df.drop(['car_ID'], axis=1, inplace=True)

## Analyze marque_voiture column

In [94]:
df['marque_voiture'].unique()

array(['alfa-romero giulia', 'alfa-romero stelvio',
       'alfa-romero Quadrifoglio', 'audi 100 ls', 'audi 100ls',
       'audi fox', 'audi 5000', 'audi 4000', 'audi 5000s (diesel)',
       'bmw 320i', 'bmw x1', 'bmw x3', 'bmw z4', 'bmw x4', 'bmw x5',
       'chevrolet impala', 'chevrolet monte carlo', 'chevrolet vega 2300',
       'dodge rampage', 'dodge challenger se', 'dodge d200',
       'dodge monaco (sw)', 'dodge colt hardtop', 'dodge colt (sw)',
       'dodge coronet custom', 'dodge dart custom',
       'dodge coronet custom (sw)', 'honda civic', 'honda civic cvcc',
       'honda accord cvcc', 'honda accord lx', 'honda civic 1500 gl',
       'honda accord', 'honda civic 1300', 'honda prelude',
       'honda civic (auto)', 'isuzu MU-X', 'isuzu D-Max ',
       'isuzu D-Max V-Cross', 'jaguar xj', 'jaguar xf', 'jaguar xk',
       'maxda rx3', 'maxda glc deluxe', 'mazda rx2 coupe', 'mazda rx-4',
       'mazda glc deluxe', 'mazda 626', 'mazda glc', 'mazda rx-7 gs',
       'mazda glc 

In [95]:
# Split the marque_voiture column into marque and modele
df['marque_voiture'] = df['marque_voiture'].str.strip()
df[['marque', 'modele']] = df['marque_voiture'].str.split(' ', 1, expand=True)
df.drop('marque_voiture', axis=1, inplace=True)

/var/folders/d0/hykm8r4n4ygf9ms5__0w6f1r0000gn/T/ipykernel_2701/1816901120.py:3: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df[['marque', 'modele']] = df['marque_voiture'].str.split(' ', 1, expand=True)


In [96]:
df

etat_de_route carburant  turbo nombre_portes type_vehicule transmission  \
0                3       gas    std           two   convertible          rwd   
1                3       gas    std           two   convertible          rwd   
2                1       gas    std           two     hatchback          rwd   
3                2       gas    std          four         sedan          fwd   
4                2       gas    std          four         sedan          4wd   
..             ...       ...    ...           ...           ...          ...   
200             -1       gas    std          four         sedan          rwd   
201             -1       gas  turbo          four         sedan          rwd   
202             -1       gas    std          four         sedan          rwd   
203             -1    diesel  turbo          four         sedan          rwd   
204             -1       gas  turbo          four         sedan          rwd   

    emplacement_moteur  empattement  longueur_voiture  largeur_voiture  ...  \
0                front         88.6             168.8             64.1  ...   
1                front         88.6             168.8             64.1  ...   
2                front         94.5             171.2             65.5  ...   
3                front         99.8             176.6             66.2  ...   
4                front         99.4             176.6             66.4  ...   
..                 ...          ...               ...              ...  ...   
200              front        109.1             188.8             68.9  ...   
201              front        109.1             188.8             68.8  ...   
202              front        109.1             188.8             68.9  ...   
203              front        109.1             188.8             68.9  ...   
204              front        109.1             188.8             68.9  ...   

     taux_alésage  course taux_compression chevaux  tour_moteur  \
0            3.47    2.68              9.0     111         5000   
1            3.47    2.68              9.0     111         5000   
2            2.68    3.47              9.0     154         5000   
3            3.19    3.40             10.0     102         5500   
4            3.19    3.40              8.0     115         5500   
..            ...     ...              ...     ...          ...   
200          3.78    3.15              9.5     114         5400   
201          3.78    3.15              8.7     160         5300   
202          3.58    2.87              8.8     134         5500   
203          3.01    3.40             23.0     106         4800   
204          3.78    3.15              9.5     114         5400   

    consommation_ville  consommation_autoroute     prix       marque  \
0                   21                      27  13495.0  alfa-romero   
1                   21                      27  16500.0  alfa-romero   
2                   19                      26  16500.0  alfa-romero   
3                   24                      30  13950.0         audi   
4                   18                      22  17450.0         audi   
..                 ...                     ...      ...          ...   
200                 23                      28  16845.0        volvo   
201                 19                      25  19045.0        volvo   
202                 18                      23  21485.0        volvo   
203                 26                      27  22470.0        volvo   
204                 19                      25  22625.0        volvo   

           modele  
0          giulia  
1         stelvio  
2    Quadrifoglio  
3          100 ls  
4           100ls  
..            ...  
200     145e (sw)  
201         144ea  
202         244dl  
203           246  
204         264gl  

[205 rows x 26 columns]

## Carburant column

In [97]:
# Want rename gas to essence
df['carburant'] = df['carburant'].replace('gas', 'essence')
df['carburant'].unique()

array(['essence', 'diesel'], dtype=object)

## nombre_portes colunm - Change values

In [98]:
df['nombre_portes'].unique()

array(['two', 'four'], dtype=object)

In [99]:
# Replace the values in the nombre_portes column
df['nombre_portes'] = df['nombre_portes'].replace({'two': 2, 'four': 4})

## type_vehicule column - Change values

In [100]:
df['type_vehicule'].unique()

array(['convertible', 'hatchback', 'sedan', 'wagon', 'hardtop'],
      dtype=object)

In [101]:
df['type_vehicule'] = df['type_vehicule'].replace({'convertible': 'cabriolet', 'hatchback': 'hayon', 'sedan': 'berline', 'wagon': 'break', 'hardtop': 'coupé'})

## transmission column - change values

In [102]:
df['transmission'].unique()

array(['rwd', 'fwd', '4wd'], dtype=object)

In [103]:
df['transmission'] = df['transmission'].replace({'rwd': 'propulsion', 'fwd': 'traction', '4wd': 'quatre_roues_motrices'}, inplace=True)

## emplacement_moteur column - change values

In [104]:
df['emplacement_moteur'].unique()

array(['front', 'rear'], dtype=object)

In [105]:
df['emplacement_moteur'] = df['emplacement_moteur'].replace({'front': 'avant', 'rear': 'arrière'}, inplace=True)

## Convert values inches to centimeters

In [106]:
def convert_to_centimeters(value):
    return value * 2.54

### Before convert

In [107]:
df['longueur_voiture'].unique()

array([168.8, 171.2, 176.6, 177.3, 192.7, 178.2, 176.8, 189. , 193.8,
       197. , 141.1, 155.9, 158.8, 157.3, 174.6, 173.2, 144.6, 150. ,
       163.4, 157.1, 167.5, 175.4, 169.1, 170.7, 172.6, 199.6, 191.7,
       159.1, 166.8, 169. , 177.8, 175. , 190.9, 187.5, 202.6, 180.3,
       208.1, 199.2, 178.4, 173. , 172.4, 165.3, 170.2, 165.6, 162.4,
       173.4, 181.7, 184.6, 178.5, 186.7, 198.9, 167.3, 168.9, 175.7,
       181.5, 186.6, 156.9, 157.9, 172. , 173.5, 173.6, 158.7, 169.7,
       166.3, 168.7, 176.2, 175.6, 183.5, 187.8, 171.7, 159.3, 165.7,
       180.2, 183.1, 188.8])

In [108]:
df['largeur_voiture'].unique()

array([64.1, 65.5, 66.2, 66.4, 66.3, 71.4, 67.9, 64.8, 66.9, 70.9, 60.3,
       63.6, 63.8, 64.6, 63.9, 64. , 65.2, 62.5, 66. , 61.8, 69.6, 70.6,
       64.2, 65.7, 66.5, 66.1, 70.3, 71.7, 70.5, 72. , 68. , 64.4, 65.4,
       68.4, 68.3, 65. , 72.3, 66.6, 63.4, 65.6, 67.7, 67.2, 68.9, 68.8])

In [109]:
df['hauteur_voiture'].unique()

array([48.8, 52.4, 54.3, 53.1, 55.7, 55.9, 52. , 53.7, 56.3, 53.2, 50.8,
       50.6, 59.8, 50.2, 52.6, 54.5, 58.3, 53.3, 54.1, 51. , 53.5, 51.4,
       52.8, 47.8, 49.6, 55.5, 54.4, 56.5, 58.7, 54.9, 56.7, 55.4, 54.8,
       49.4, 51.6, 54.7, 55.1, 56.1, 49.7, 56. , 50.5, 55.2, 52.5, 53. ,
       59.1, 53.9, 55.6, 56.2, 57.5])

In [110]:
df['empattement'].unique()

array([ 88.6,  94.5,  99.8,  99.4, 105.8,  99.5, 101.2, 103.5, 110. ,
        88.4,  93.7, 103.3,  95.9,  86.6,  96.5,  94.3,  96. , 113. ,
       102. ,  93.1,  95.3,  98.8, 104.9, 106.7, 115.6,  96.6, 120.9,
       112. , 102.7,  93. ,  96.3,  95.1,  97.2, 100.4,  91.3,  99.2,
       107.9, 114.2, 108. ,  89.5,  98.4,  96.1,  99.1,  93.3,  97. ,
        96.9,  95.7, 102.4, 102.9, 104.5,  97.3, 104.3, 109.1])

In [111]:
df['longueur_voiture'], df['largeur_voiture'], df['hauteur_voiture'], df['empattement'] = df['longueur_voiture'].apply(convert_to_centimeters), df['largeur_voiture'].apply(convert_to_centimeters), df['hauteur_voiture'].apply(convert_to_centimeters), df['empattement'].apply(convert_to_centimeters)

### After convert

In [112]:
df['longueur_voiture'].unique()

array([428.752, 434.848, 448.564, 450.342, 489.458, 452.628, 449.072,
       480.06 , 492.252, 500.38 , 358.394, 395.986, 403.352, 399.542,
       443.484, 439.928, 367.284, 381.   , 415.036, 399.034, 425.45 ,
       445.516, 429.514, 433.578, 438.404, 506.984, 486.918, 404.114,
       423.672, 429.26 , 451.612, 444.5  , 484.886, 476.25 , 514.604,
       457.962, 528.574, 505.968, 453.136, 439.42 , 437.896, 419.862,
       432.308, 420.624, 412.496, 440.436, 461.518, 468.884, 453.39 ,
       474.218, 505.206, 424.942, 429.006, 446.278, 461.01 , 473.964,
       398.526, 401.066, 436.88 , 440.69 , 440.944, 403.098, 431.038,
       422.402, 428.498, 447.548, 446.024, 466.09 , 477.012, 436.118,
       404.622, 420.878, 457.708, 465.074, 479.552])

In [113]:
df['largeur_voiture'].unique()

array([162.814, 166.37 , 168.148, 168.656, 168.402, 181.356, 172.466,
       164.592, 169.926, 180.086, 153.162, 161.544, 162.052, 164.084,
       162.306, 162.56 , 165.608, 158.75 , 167.64 , 156.972, 176.784,
       179.324, 163.068, 166.878, 168.91 , 167.894, 178.562, 182.118,
       179.07 , 182.88 , 172.72 , 163.576, 166.116, 173.736, 173.482,
       165.1  , 183.642, 169.164, 161.036, 166.624, 171.958, 170.688,
       175.006, 174.752])

In [114]:
df['hauteur_voiture'].unique()

array([123.952, 133.096, 137.922, 134.874, 141.478, 141.986, 132.08 ,
       136.398, 143.002, 135.128, 129.032, 128.524, 151.892, 127.508,
       133.604, 138.43 , 148.082, 135.382, 137.414, 129.54 , 135.89 ,
       130.556, 134.112, 121.412, 125.984, 140.97 , 138.176, 143.51 ,
       149.098, 139.446, 144.018, 140.716, 139.192, 125.476, 131.064,
       138.938, 139.954, 142.494, 126.238, 142.24 , 128.27 , 140.208,
       133.35 , 134.62 , 150.114, 136.906, 141.224, 142.748, 146.05 ])

In [115]:
df['empattement'].unique()

array([225.044, 240.03 , 253.492, 252.476, 268.732, 252.73 , 257.048,
       262.89 , 279.4  , 224.536, 237.998, 262.382, 243.586, 219.964,
       245.11 , 239.522, 243.84 , 287.02 , 259.08 , 236.474, 242.062,
       250.952, 266.446, 271.018, 293.624, 245.364, 307.086, 284.48 ,
       260.858, 236.22 , 244.602, 241.554, 246.888, 255.016, 231.902,
       251.968, 274.066, 290.068, 274.32 , 227.33 , 249.936, 244.094,
       251.714, 236.982, 246.38 , 246.126, 243.078, 260.096, 261.366,
       265.43 , 247.142, 264.922, 277.114])